apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- github.com/leon-victor/order-service/k8s?ref=main

patchesStrategicMerge:
- patch-env.yml
- patch-resources.yml
- patch-volumes.yml

configMapGenerator:
- behavior: merge
  files:
  - application-prod.yml
  name: order-config

images:
- name: order-service
  newName: ghcr.io/leon-victor/order-service
  newTag: 1a8b0b682949e3f60f8ce51466c77edaa65ed002

replicas:
- count: 1
  name: order-service
